Output translation-demo.gif
Set FontSize 32
Set Width 2200
Set Height 600

Sleep 2s

Type@100ms "chatgpt-cli chat"
Sleep 2s
Enter
# Admire the output for a bit.
Sleep 8s

Type@250ms "Say hello in Japanese"
Sleep 2s
Enter
Tab

Sleep 8s
Ctrl+C
Sleep 4s

Type@100ms "chatgpt-cli chat --session-file chatgpt-cli-*.json"
Sleep 2s
Enter
Sleep 5s

Type@300ms "and in Korean"
Sleep 2s
Enter
Tab

Sleep 8s
Ctrl+C

# Admire the output for a bit.
Sleep 10s