name: Go CI Build

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  go-versions:
    name: Lookup Go versions
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.versions.outputs.matrix }}
    steps:
      - uses: actions/checkout@v7
      - uses: arnested/go-version-action@6ccff891beb7200dc4a3389378c726c75b7d4b1e
        id: versions

  build:
    name: Test
    runs-on: ubuntu-latest
    needs: go-versions
    strategy:
      matrix:
        version: ${{ fromJSON(needs.go-versions.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version: ${{ matrix.version }}

      - name: Go Version
        run: go version

      - name: Test
        run: make test

      - name: GoReleaser Check
        uses: goreleaser/goreleaser-action@v7
        with:
          version: '~> v2'
          args: check
          workdir: .

      - name: GoReleaser Build
        uses: goreleaser/goreleaser-action@v7
        with:
          version: '~> v2'
          args: build --snapshot --clean --single-target --output .
          workdir: .
